# Created with YamlCreate.ps1 v2.4.3 $debug=NVS1.CRLF.5-1-26100-2161.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: SE.PowerChutePE
PackageVersion: 3.1.0
InstallerLocale: en-US
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ReleaseDate: 2022-07-08
Installers:
- Architecture: x86
  InstallerUrl: https://download.schneider-electric.com/files?p_Doc_Ref=APC_PCPE_310
  InstallerSha256: 06CDB01B2E23ED72452FF090212BA72B5A250C16C41485ECD05D4AC9F75E25FF
ManifestType: installer
ManifestVersion: 1.9.0
