# Created with YamlCreate.ps1 v2.4.3 $debug=NVS1.CRLF.5-1-26100-2161.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Auslogics.DiskDefragUltimate
PackageVersion: 4.13.0.2
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
  - silent
  - silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2024-07-03
Installers:
  - Architecture: x86
    InstallerUrl: https://downloads.auslogics.com/en/disk-defrag-ultimate/auslogics-disk-defrag-ultimate-setup.exe
    InstallerSha256: F4ED498E5DCDB8DD0B219BD0580AB2DE1ED31E1B13962675895D5D3327E4633A
ManifestType: installer
ManifestVersion: 1.9.0
